jobs:
  nightly:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clean up previous run
      run: 'echo "Cleaning up previous run"

        cd $RUNNER_WORKSPACE

        pwd

        cd ..

        pwd

        rm -rf _tool

        '
    - continue-on-error: true
      name: Setup Python 3.9
      uses: actions/setup-python@v5
      with:
        architecture: x64
        python-version: 3.9
    - continue-on-error: true
      name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      name: Checkout TorchServe
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - continue-on-error: true
      name: Install dependencies
      run: 'sudo apt-get update -y

        sudo apt-get install -y apache2-utils

        pip install -r benchmarks/requirements-ab.txt

        '
    - continue-on-error: true
      if: ${{ matrix.hardware == 'cpu' }}
      name: Benchmark cpu nightly
      run: python benchmarks/auto_benchmark.py --input benchmarks/benchmark_config_cpu.yaml
        --skip false
    - continue-on-error: true
      if: ${{ matrix.hardware == 'gpu' }}
      name: Benchmark gpu nightly
      run: python benchmarks/auto_benchmark.py --input benchmarks/benchmark_config_gpu.yaml
        --skip false
    - continue-on-error: true
      env:
        NEURON_RT_NUM_CORES: 1
      if: ${{ matrix.hardware == 'inf2' }}
      name: Benchmark inf2 nightly
      run: python benchmarks/auto_benchmark.py --input benchmarks/benchmark_config_neuronx.yaml
        --skip false
    - continue-on-error: true
      name: Save benchmark artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nightly ${{ matrix.hardware }} artifact
        path: /tmp/ts_benchmark
    - continue-on-error: true
      name: Download benchmark artifacts for auto validation
      uses: dawidd6/action-download-artifact@v2
      with:
        if_no_artifact_found: ignore
        name: ${{ matrix.hardware }}_benchmark_validation
        path: /tmp/ts_artifacts
        workflow: ${{ github.event.workflow_run.workflow_id }}
        workflow_conclusion: success
    - continue-on-error: true
      name: Validate Benchmark result
      run: python benchmarks/validate_report.py --input-artifacts-dir /tmp/ts_artifacts/${{
        matrix.hardware }}_benchmark_validation
    - continue-on-error: true
      name: Update benchmark artifacts for auto validation
      run: python benchmarks/utils/update_artifacts.py --output /tmp/ts_artifacts/${{
        matrix.hardware }}_benchmark_validation
    - continue-on-error: true
      name: Upload the updated benchmark artifacts for auto validation
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.hardware }}_benchmark_validation
        path: /tmp/ts_artifacts
    - continue-on-error: true
      if: ${{ failure() && github.event_name  == 'schedule' && matrix.hardware ==
        'cpu' }}
      name: Open issue on failure
      uses: dacbd/create-issue-action@v1
      with:
        assignees: ''
        body: Commit ${{ github.sha }} daily scheduled [CI run](https://github.com/${{
          github.repository }}/actions/runs/${{ github.run_id }}) failed, please check
          why
        title: Nightly ${{ matrix.hardware }} benchmark failed
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        hardware:
        - cpu
        - gpu
        - inf2
    timeout-minutes: 1320
name: Benchmark torchserve nightly
on:
  repository_dispatch:
    types: trigger-ga___benchmark_nightly.yml
