jobs:
  nightly:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clean up previous run
      run: 'echo "Cleaning up previous run"

        cd $RUNNER_WORKSPACE

        pwd

        cd ..

        pwd

        rm -rf _tool

        '
    - continue-on-error: true
      name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        architecture: x64
        python-version: '3.10'
    - continue-on-error: true
      name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      name: Checkout TorchServe
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - continue-on-error: true
      name: Install dependencies
      run: 'sudo apt-get update -y

        sudo apt-get install -y apache2-utils

        pip install -r benchmarks/requirements-ab.txt

        '
    - continue-on-error: true
      name: Install model-specific dependencies
      run: 'chmod +x benchmarks/benchmark_model_dependencies.sh

        source benchmarks/benchmark_model_dependencies.sh

        '
    - continue-on-error: true
      name: Benchmark gpu nightly
      run: python benchmarks/auto_benchmark.py --input benchmarks/benchmark_config_torch_compile_gpu.yaml
        --skip false --nightly True
    strategy:
      fail-fast: false
    timeout-minutes: 1320
name: Benchmark torch.compile models nightly
on:
  repository_dispatch:
    types: trigger-ga___benchmark_torch_compile_nightly.yml
