concurrency:
  cancel-in-progress: true
  group: ci-cpu-${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number
    || github.ref }}
jobs:
  ci-cpu-cpp:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: matrix.os != 'macos-14'
      name: Setup Python for all other OS
      uses: actions/setup-python@v5
      with:
        architecture: x64
        python-version: 3.9
    - continue-on-error: true
      name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      name: Checkout TorchServe
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - continue-on-error: true
      name: Install dependencies
      run: 'sudo apt update && python ts_scripts/install_dependencies.py --environment=dev
        --cpp

        '
    - continue-on-error: true
      name: Install TorchServe
      run: 'python ts_scripts/install_from_src.py

        '
    - continue-on-error: true
      name: Print Env
      run: 'python ts_scripts/print_env_info.py

        '
    - continue-on-error: true
      name: Build
      run: 'cd cpp && rm -rf _build && sudo mkdir /mnt/_build && sudo chmod 777 /mnt/_build
        && mkdir build && sudo mount --bind /mnt/_build build

        cd build && cmake ..

        make -j && make install

        make test

        '
    - continue-on-error: true
      name: Run test
      run: 'cd test && pytest pytest/test_cpp_backend.py

        '
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
name: CI CPU - CPP Build
on:
  repository_dispatch:
    types: trigger-ga___ci-cpu-cpp.yml
