concurrency:
  cancel-in-progress: true
  group: ci-gpu-${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number
    || github.ref }}
jobs:
  ci-gpu:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clean up previous run
      run: 'echo "Cleaning up previous run"

        ls -la ./

        # deletes all files in the current directory

        sudo rm -rf ./* || true

        # deletes all hidden files in a directory

        sudo rm -rf ./.??* || true

        ls -la ./

        '
    - continue-on-error: true
      name: Setup Python 3.9
      uses: actions/setup-python@v5
      with:
        architecture: x64
        python-version: 3.9
    - continue-on-error: true
      name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      name: Checkout TorchServe
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - continue-on-error: true
      name: Install dependencies
      run: 'python ts_scripts/install_dependencies.py --environment=dev --cuda=cu121

        '
    - continue-on-error: true
      name: Torchserve Sanity
      uses: nick-fields/retry@v3
      with:
        command: 'python torchserve_sanity.py

          '
        max_attempts: 3
        retry_on: error
        timeout_minutes: 60
    - continue-on-error: true
      name: Upload codecov
      run: 'curl -Os https://uploader.codecov.io/latest/linux/codecov

        chmod +x codecov

        ./codecov

        '
name: CI GPU
on:
  repository_dispatch:
    types: trigger-ga___ci_gpu.yml
