jobs:
  build_docs_job:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Setup Python 3.9
      uses: actions/setup-python@v5
      with:
        architecture: x64
        python-version: 3.9
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Install Dependencies
      run: 'pip install -r ./docs/sphinx/requirements.txt

        '
    - continue-on-error: true
      id: build
      name: Build the docset
      run: 'cd ./docs/sphinx

        make html

        '
    - continue-on-error: true
      name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        CLEAN_EXCLUDE: '["_config.yml"]'
        FOLDER: docs/sphinx/build/html
    - continue-on-error: true
      if: ${{ failure() && github.event_name  == 'schedule' }}
      name: Open issue on failure
      uses: dacbd/create-issue-action@v1
      with:
        assignees: ''
        body: Commit ${{ github.sha }} daily scheduled [CI run](https://github.com/${{
          github.repository }}/actions/runs/${{ github.run_id }}) failed, please check
          why
        title: Doc automation failed
        token: ${{ secrets.GITHUB_TOKEN }}
on:
  repository_dispatch:
    types: trigger-ga___doc-automation.yml
