jobs:
  kserve-cpu-tests:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clean up previous run
      run: 'echo "Cleaning up previous run"

        ls -la ./

        sudo rm -rf ./* || true

        sudo rm -rf ./.??* || true

        ls -la ./

        '
    - continue-on-error: true
      name: Install minikube and kubectl
      run: 'curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64

        sudo install minikube-linux-amd64 /usr/local/bin/minikube

        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

        echo "/usr/local/bin" >> $GITHUB_PATH

        '
    - continue-on-error: true
      name: Setup Python 3.9
      uses: actions/setup-python@v5
      with:
        architecture: x64
        python-version: 3.9
    - continue-on-error: true
      name: Install grpcurl
      run: 'sudo curl -sSL https://github.com/fullstorydev/grpcurl/releases/download/v1.8.0/grpcurl_1.8.0_linux_x86_64.tar.gz
        | sudo tar -xz -C /usr/local/bin grpcurl

        sudo chmod +x /usr/local/bin/grpcurl

        '
    - continue-on-error: true
      name: Checkout TorchServe
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Checkout kserve repo
      uses: actions/checkout@v4
      with:
        path: kserve
        ref: v0.12.0
        repository: kserve/kserve
    - continue-on-error: true
      name: Validate torchserve-kfs and Open Inference Protocol
      run: ./kubernetes/kserve/tests/scripts/test_mnist.sh
name: KServe CPU Nightly Tests
on:
  repository_dispatch:
    types: trigger-ga___kserve_cpu_tests.yml
