jobs:
  official-release-docker:
    environment:
      name: official-release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clean up previous run
      run: 'echo "Cleaning up previous run"

        ls -la ./

        sudo rm -rf ./* || true

        sudo rm -rf ./.??* || true

        ls -la ./

        '
    - continue-on-error: true
      name: Setup Python 3.9
      uses: actions/setup-python@v5
      with:
        architecture: x64
        python-version: 3.9
    - continue-on-error: true
      name: Checkout TorchServe
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - continue-on-error: true
      env:
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      name: Login to Docker
      run: docker login --username pytorchbot --password "$DOCKER_PASSWORD"
    - continue-on-error: true
      if: github.event.inputs.upload_docker == 'yes'
      name: Build & Upload pytorch/torchserve Docker images
      run: 'cd docker

        python build_upload_release.py --cleanup

        '
    - continue-on-error: true
      if: github.event.inputs.upload_kfs == 'yes'
      name: Build & Upload pytorch/torchserve-kfs Docker images
      run: 'cd kubernetes/kserve

        python build_upload_release.py --cleanup

        '
name: Make an official Release of Docker Images
on:
  repository_dispatch:
    types: trigger-ga___official_release_docker.yml
