jobs:
  official-release:
    environment:
      name: official-release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: true
        python-version: '3.9'
        update-conda: false
    - continue-on-error: true
      name: Setup Anaconda
      run: 'conda --version

        conda install -y conda-build anaconda-client

        '
    - continue-on-error: true
      name: Checkout TorchServe
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Install dependencies
      run: 'python ts_scripts/install_dependencies.py --environment=dev

        pip install -e .

        '
    - continue-on-error: true
      name: Setup Java 17
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      name: Build PyPI & conda binaries
      run: python binaries/build.py
    - continue-on-error: true
      env:
        ANACONDA_API_TOKEN: ${{ secrets.CONDA_PASSWORD }}
      name: Push conda binaries
      run: python binaries/upload.py --upload-conda-packages
    - continue-on-error: true
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      name: Push PyPI binaries
      run: python binaries/upload.py --upload-pypi-packages
name: Make an official Release
on:
  repository_dispatch:
    types: trigger-ga___official_release.yml
