concurrency:
  cancel-in-progress: true
  group: ci-cpu-${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number
    || github.ref }}
jobs:
  regression-gpu-nightly-binaries:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clean up previous run
      run: 'echo "Cleaning up previous run"

        ls -la ./

        sudo rm -rf ./* || true

        sudo rm -rf ./.??* || true

        ls -la ./

        '
    - continue-on-error: true
      name: Checkout TorchServe
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - continue-on-error: true
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        python-version: ${{ matrix.python-version }}
    - continue-on-error: true
      name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        architecture: x64
        python-version: ${{ matrix.python-version }}
    - continue-on-error: true
      run: python --version
    - continue-on-error: true
      run: conda --version
    - continue-on-error: true
      name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      name: Install dependencies
      run: 'echo "=====CHECK ENV AND PYTHON VERSION===="

        /home/ubuntu/actions-runner/_work/serve/serve/3/condabin/conda info --envs

        python --version

        echo "=====RUN INSTALL DEPENDENCIES===="

        python ts_scripts/install_dependencies.py --environment=dev --cuda=cu121

        '
      shell: bash -el {0}
    - continue-on-error: true
      name: Torchserve Regression Tests
      run: 'echo "=====CHECK ENV AND PYTHON VERSION===="

        /home/ubuntu/actions-runner/_work/serve/serve/3/condabin/conda info --envs

        python --version

        echo "=====RUN REGRESSION TESTS===="

        python test/regression_tests.py --binaries --${{ matrix.binaries }} --nightly

        '
      shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        binaries:
        - pypi
        - conda
        python-version:
        - '3.8'
        - '3.9'
        - '3.10'
name: Run Regression Tests for GPU nightly binaries
on:
  repository_dispatch:
    types: trigger-ga___regression_tests_gpu_binaries.yml
