concurrency:
  cancel-in-progress: true
  group: ci-cpu-${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number
    || github.ref }}
jobs:
  regression-cpu:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: matrix.os == 'macos-latest'
      name: Setup Python for M1
      uses: actions/setup-python@v5
      with:
        architecture: arm64
        python-version: '3.10'
    - continue-on-error: true
      if: matrix.os != 'macos-latest'
      name: Setup Python for all other OS
      uses: actions/setup-python@v5
      with:
        architecture: x64
        python-version: '3.9'
    - continue-on-error: true
      name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      name: Checkout TorchServe
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - continue-on-error: true
      name: Install dependencies
      run: 'python ts_scripts/install_dependencies.py --environment=dev

        '
    - continue-on-error: true
      env:
        TS_MAC_ARM64_CPU_ONLY: ${{ matrix.os == 'macos-latest' && 'True' || 'False'
          }}
      name: Torchserve Regression Tests
      run: 'python test/regression_tests.py

        '
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        - macos-latest
name: Run Regression Tests on CPU
on:
  repository_dispatch:
    types: trigger-ga___regression_tests_cpu.yml
