jobs:
  nightly:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: true
        python-version: '3.9'
        update-conda: false
    - continue-on-error: true
      run: conda --version
    - continue-on-error: true
      run: conda install -y conda-build anaconda-client
    - continue-on-error: true
      name: Checkout TorchServe
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - continue-on-error: true
      name: Install dependencies
      run: 'python ts_scripts/install_dependencies.py --environment=dev

        pip install -e .

        '
    - continue-on-error: true
      name: Setup Java 17
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      name: Build PyPI & conda nightly binaries
      run: python binaries/build.py --nightly
    - continue-on-error: true
      env:
        ANACONDA_API_TOKEN: ${{ secrets.CONDA_NIGHTLY_TOKEN }}
      name: Push conda nightly binaries
      run: python binaries/upload.py --upload-conda-packages
    - continue-on-error: true
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      name: Push PyPI nightly binaries
      run: python binaries/upload.py --upload-pypi-packages
    - continue-on-error: true
      if: ${{ failure() && github.event_name  == 'schedule' }}
      name: Open issue on failure
      uses: dacbd/create-issue-action@v1
      with:
        assignees: ''
        body: Commit ${{ github.sha }} daily scheduled [CI run](https://github.com/${{
          github.repository }}/actions/runs/${{ github.run_id }}) failed, please check
          why
        title: Nightly Build failed
        token: ${{ secrets.GITHUB_TOKEN }}
name: Push torchserve nightly
on:
  repository_dispatch:
    types: trigger-ga___torchserve-nightly-build.yml
